name: 'Setup and Build'
description: 'Sets up Node.js and builds the project'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      shell: bash
      run: npm ci
      
    - name: Build project
      shell: bash
      run: npm run build